server:
  port: 9090

spring:
  profiles:
    active: ${ACTIVE_PROFILE:development} # se a variavel active_profile for nula, usa o perfil de development

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:9999/curso}
    username: ${USERNAME_DEV:postgres}
    password: ${PASSWORD_DEV:postgres}
    hikari: #Auxilia a demanda e concorrência das conexões
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 3
---
spring:
  config:
    activate:
      on-profile: production
